import AddIcon from './AddIcon.svg?react'
import DeleteIcon from './DeleteIcon.svg?react'
import ChineseIcon from './ChineseIcon.svg?react'
import EnglishIcon from './EnglishIcon.svg?react'
import LogoIcon from './LogoIcon.svg?react'
import EditIcon from './EditIcon.svg?react'
import ListIcon from './ListIcon.svg?react'
import HomeIcon from './HomeIcon.svg?react'
import ProductIcon from './ProductIcon.svg?react'
import UserIcon from './UserIcon.svg?react'
import OrderIcon from './OrderIcon.svg?react'
import MarketingIcon from './MarketingIcon.svg?react'
import ViewIcon from './ViewIcon.svg?react'
import SendIcon from './SendIcon.svg?react'
import CategoryIcon from './CategoryIcon.svg?react'
import VideoIcon from './VideoIcon.svg?react'

export { AddIcon, DeleteIcon, ChineseIcon, EnglishIcon, LogoIcon, EditIcon, ListIcon, HomeIcon, ProductIcon, UserIcon, OrderIcon, MarketingIcon, ViewIcon, SendIcon, CategoryIcon, VideoIcon }